items_no_pref <- c("The company\'s vision is very clear.",
"I can summarize the company\'s vision to someone I meet.",
"I feel inspired by the company\'s vision.",
"Leaders are passionate about the company\'s vision.",
"Leaders are guided by the company\'s vision.",
"I have confidence in the company\'s strategy.",
"I know what my company wants to achieve in the next year.",
"This company knows how to get the results it is looking for.",
"We know what our next step is for improving our capabilities.",
"Leadership effectively connects my work to the company goals.",
"I have a great deal of confidence in the leadership of this company.",
"Company leaders impact the attitude and culture of the entire company.",
"The leadership of this company is fantastic in comparison to the leadership of other organizations I\'ve been involved with.",
"Leaders find the time to get to know the employees.",
"I have confidence in the decision making of company leaders.",
"We deal with the same problems again and again.*",
"Company changes usually have a positive impact on me.",
"People look to pass the blame when something goes wrong.*",
"If an issue arises, people mostly remain calm and focused.",
"We use feedback from customers to improve our services.",
"I have real time access to business i.",
"My team uses performance measures (i.e. key performance indicators).",
"We are recognized for our successes.",
"We have a clear sense at all times whether or not we\'re meeting our objectives.",
"We are held accountable for our performance.",
"I often use \'workarounds\' instead of the company\'s established systems.*",
"It often takes too long to get the information I need.*",
"Oftentimes, I have to take care of things that shouldn\'t be my responsibility.*",
"I know who to go to when I have concerns about our systems/processes.",
"I follow the company\'s standardized procedures.",
"Our team consistently meets our goals.",
"Our work would be better if we collaborated more.",
"Our skills complement each other well.",
"There\'s a real sense that I am part of a team.",
"Our company has a spirit of teamwork and cooperation.",
"My company does a good job of hiring the right people for the right jobs.",
"I am confident my performance affects my compensation.",
"I get along well with my supervisor.",
"Performance reviews are a waste of time.*",
"Based on my experience, the company does a great job of acclimating new employees.",
"I get helpful feedback from my supervisor on a regular basis.",
"I am consistently improving at my job.",
"People here are always willing to help me learn.",
"The company invests in employees learning new skills.",
"I have grown professionally during my time with this company.",
"My job role is always extremely clear.",
"I am very frequently overwhelmed at work.*",
"My job is a great fit for my skills and strengths.",
"I embrace the company\'s core values.",
"I look forward to going to work.",
"I believe in the products or services we provide.",
"I respond to customer needs as quickly as possible.",
"I build great relationships with my customers.",
"I\'m disappointed if I don\'t meet my customers\' expectations.",
"I seek feedback from customers to improve our products or services.",
"My opinions are heard and valued.",
"I am confident that leadership understands what I do.",
"I am very comfortable letting my supervisor know when I\'ve made a mistake.",
"I trust my supervisor has my best interest in mind.",
"I feel micromanaged.*",
"People in my organization express genuine gratitude toward one another.",
"I practice mindfulness by staying in the present moment while doing my work.",
"People I work with generally feel optimistic about the organization\'s future.",
"People that I work with care about my happiness and well-being.",
"I feel inspired every day to do my best work.",
"Taking everything into consideration, I am satisfied with my job as a whole.",
"I am willing to put in a great deal of effort beyond what is normally expected in order to help the organization.")